snow:
  worker-id: 1
spring:
  profiles:
    active: local
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      database: ${redis.database}
      password: ${redis.password}

  datasource:
    url: ${spring.db.url}
    username: ${spring.db.username}
    password: ${spring.db.password}
  jwt:
    secret: ${bili-chat.jwt.secret}
  oss:
    endpoint: ${OSS.endpoint}
    accessKeyId: ${OSS.accessKeyId}
    accessKeySecret: ${OSS.accessKeySecret}
    bucketName: ${OSS.bucket}
    domain: ${OSS.region}
cos:
  client:
    secret-id: ${COS.secretId}
    secret-key: ${COS.secretKey}
    region: ${COS.region}
    bucket: ${COS.bucket}
    host: ${COS.host}
#    bucket-name: ${COS.}